# Use a lightweight Python base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install required dependencies
RUN apt-get update && apt-get install -y libpq-dev gcc && \
    pip3 install --no-cache-dir psycopg2-binary pandas numpy

# Copy scripts into the container
COPY . /app
